### ISSUE TITLE
Add support to send logs from a custom directory/file

### ISSUE THREAD

**Issue by KadenLNelson** [blacktop/docker-es-demo-data#1]
Add a volume mount like `-v "/var/log/nginx":"/var/logs"`? It seems like there is a lot of boilerplate code to get logs into your elastic stack. If others would like to tryout their own logs with the stack, it may be helpful to add a volume mount.

**Comment by blacktop** [comment]
Kibana actually total "ripped me off" j/k lol and now you can add data from right within the GUI to get some demo data to play with so this repo is kinda useless now.

See **One-click sample data** - https://www.elastic.co/blog/kibana-6-4-0-released
